apiVersion: v1
kind: Namespace
metadata:
  name: dokus-production
  labels:
    name: dokus-production
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: dokus-staging
  labels:
    name: dokus-staging
    environment: staging
