name: Build

on:
  workflow_call:
    inputs:
      shouldRunKmp:
        required: true
        type: string
      shouldRunAndroid:
        required: true
        type: string
      shouldRunIos:
        required: true
        type: string
      shouldRunDesktop:
        required: true
        type: string
      shouldRunWasm:
        required: true
        type: string

jobs:
  Android:
    if: ${{ inputs.shouldRunKmp == 'true' || inputs.shouldRunAndroid == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Job set up
        uses: ./.github/actions/job-set-up

      - run: ./gradlew :composeApp:assembleDebug

  Desktop:
    if: ${{ inputs.shouldRunKmp == 'true' || inputs.shouldRunDesktop == 'true' }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Job set up
        uses: ./.github/actions/job-set-up

      - name: Build Desktop
        run: ./gradlew :composeApp:packageReleaseDmg

#      - name: Upload macOS App
#        uses: actions/upload-artifact@v4
#        with:
#          name: macOS-app
#          path: composeApp/build/compose/binaries/main-release/dmg

  iOS:
    if: ${{ inputs.shouldRunKmp == 'true' || inputs.shouldRunIos == 'true' }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Job set up
        uses: ./.github/actions/job-set-up

      - name: iOS set up
        uses: ./.github/actions/ios-set-up

      - run: xcodebuild build -workspace iosApp/iosApp.xcworkspace -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 14' -verbose

  WASM:
    if: ${{ inputs.shouldRunKmp == 'true' || inputs.shouldRunWasm == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Job set up
        uses: ./.github/actions/job-set-up

      - name: Build WASM
        run: ./gradlew wasmJsBrowserDistribution

#      - name: Deploy to GitHub Pages
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: build/dist/wasmJs/productionExecutable